### ISSUE TITLE
Love this. Any way to extend it to the front end?

### ISSUE THREAD

**Issue by jzeevi** [trananhmanh89/ffexplorer#3]
I really like this and have two questions:

1. Is there a way to allow front end users from a particular group to use this?

2. Would you consider adding a way to allow me to filter what is seen to (for example) my registered users group can only see a particular directory?

Thanks,

josef

**Comment by trananhmanh89** [comment]
Sorry, this is component for backend only. I have no plan to bring it to front end.

**Comment by jzeevi** [comment]
Thanks for letting me know. 

Josef
