### ISSUE TITLE
Collaboration?

### ISSUE THREAD

**Issue by Llewellynvdm** [trananhmanh89/ffexplorer#4]
Greetings I would like to know if you are willing to help me place this editor you are using in [JCB](https://github.com/vdm-io/Joomla-Component-Builder)?

What I would like to do, is then drive attention to your project, and even integrate it with JCB, so that the users of JCB can open files from JCB in your component.

Been using your tool and found it very well done, specially the editor of the code. So in JCB we are currently using the CodeMirror editor, and it is not that great. Let me know if you are willing to help me with this.

**Comment by trananhmanh89** [comment]
Sorry,
I'm kind of busy with other project, can't help you.
