### ISSUE TITLE
Database table prefix

### ISSUE THREAD

**Issue by tancetin** [trananhmanh89/ffexplorer#5]
Some table prefixes are different from joomla installation table prefixes. Tables other than the Joomla table prefix are not listed.

FFExplorere -v: 1.0.6 [Update on 2021-07-07 17:22 (GMT+3)]

System Information
PHP Built On | Linux nwcompactap 4.18.0-305.el8.x86_64 #1 SMP Thu Apr 29 08:54:30 EDT 2021 x86_64
-- | --
Database Type | mysql
Database Version | 5.5.5-10.4.19-MariaDB
Database Collation | utf8mb4_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.4.19
Web Server | Apache/2.4.47 (Unix) OpenSSL/1.1.1k PHP/7.4.19 mod_perl/2.0.11 Perl/v5.32.1
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 3.9.28 Stable [ Amani ] 6-July-2021 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36

**Comment by trananhmanh89** [comment]
Hi,
I only want to modify joomla tables. That's why i did it.

**Comment by tancetin** [comment]
Hi,
As you can imagine, it may be necessary to use the prefixes of some tables for other purposes. This situation creates a deficiency as there is no access to other tables.
Tan///

**Comment by tancetin** [comment]
Maybe you can also add the ability to make sql queries. :)

**Comment by tancetin** [comment]
have you an update?

**Comment by trananhmanh89** [comment]
> have you an update?

Sorry, i don't have any plan for this feature.
