### ISSUE TITLE
No files shown

### ISSUE THREAD

**Issue by teddyearp** [trananhmanh89/ffexplorer#6]
Using the file explorer portion, no files show in my images or most other folders.  Only the .html, .php files.  Couldn't find any settings other than permissions, which I changed to allowed and changed back to inherited.

**Comment by trananhmanh89** [comment]
Everything is showing fine at my end. Could you give me some screenshot?

![2021-08-31_103502](https://user-images.githubusercontent.com/20571336/131437610-e78b4a22-9553-4682-87be-c4691dc6c9b3.png)

**Comment by teddyearp** [comment]
_____

**Comment by trananhmanh89** [comment]
Sorry, i can't see your photo

**Comment by teddyearp** [comment]
You can't open the attachment?

Misspelled from my flip phone

**Comment by teddyearp** [comment]
Misspelled from my flip phone

**Comment by trananhmanh89** [comment]
Can't. I'm using github web.

**Comment by teddyearp** [comment]
![FFExplorerScreenshot](https://user-images.githubusercontent.com/80785009/131589013-41a43b08-9b5f-4a26-87dd-adf5a4317d5e.png)
Try that.  I was just replying to emails.  You'll see that I have one of my image folders open and all that ffexplorer shows is the index.html file. None of the .jpg files.

**Comment by trananhmanh89** [comment]
I tried to replicated your issue, but not success. Could you check that folder permission? May be there is no read permission.

![2021-09-01_105419](https://user-images.githubusercontent.com/20571336/131609155-d3c0c173-f218-4bb5-b0b1-9c03b7286c95.png)

**Comment by teddyearp** [comment]
My joomla is running on a LAMP stack and not a VM. PHP 7.4.2, MariaDB 10.x,
Apache 2.4.2.  The permissions for all my folders being served are 755 and
chmod to www-data:www-data.  My site wouldn't even work otherwise.

 

  _____

**Comment by trananhmanh89** [comment]
Hi,
You can check the code at `administrator\components\com_ffexplorer\controllers\explorer.php`
Function `explodeFolder` to see what happened.

**Comment by teddyearp** [comment]
Well, I don't know php code or I would perhaps write my own, lol. ;)  But here is what I copied from that section of the file.
[explodefolder.txt](https://github.com/trananhmanh89/ffexplorer/files/7092375/explodefolder.txt)

**Comment by trananhmanh89** [comment]
I don't see any thing wrong here. Could you share your admin info to gmail trananhmanh89 ?
