### ISSUE TITLE
Database header does not align with columns

### ISSUE THREAD

**Issue by sluc69** [trananhmanh89/ffexplorer#7]
![image](https://user-images.githubusercontent.com/82952282/137586084-05480deb-5440-4bbe-8307-b964493f0adb.png)

**Comment by trananhmanh89** [comment]
Sorry, i don't get it. Could you explain more?

**Comment by sluc69** [comment]
[image: image.png]
In this example the colum headings are out of place. Heading does nct
orrespond to the correct column

**Comment by trananhmanh89** [comment]
Sorry, but did you upload a new image?

**Comment by sluc69** [comment]
screenshot from myphpadmin showing the keys and values
![Screenshot-phpmyadmin](https://user-images.githubusercontent.com/82952282/142794317-9a73b062-b60c-4a2f-90e6-9dcf6ad4c29e.jpg)

Screen shot from FF explorer showing different keys and values
![Screenshot-FF-database](https://user-images.githubusercontent.com/82952282/142794334-a7f31397-b902-45f3-af5c-8db3d045a29b.jpg)
)
in case you need the table:
[u0fcj_virtuemart_invoices.zip](https://github.com/trananhmanh89/ffexplorer/files/7577969/u0fcj_virtuemart_invoices.zip)

**Comment by trananhmanh89** [comment]
@sluc69 i couldn't replicate your issue at my end. But you can try this patch

https://github.com/trananhmanh89/ffexplorer/commit/1c3bb58a1fd5c3db21e71dc5dfd70ccc48e8d58d

**Comment by sluc69** [comment]
I looks OK after i applied the patch. 
Thank you for the effort.
I buy you coffee and more when you come to manila ... ;-)

**Comment by trananhmanh89** [comment]
Thanks ^^

**Comment by kg-design** [comment]
Hello,

I am using the latest version of Joomla and FF explorer and I  am having the exact same issue.
Could you please help?

Joomla version: 4.3.1
FF Explorer version: 1.0.7

![ff-explorer-worng-column-name](https://github.com/trananhmanh89/ffexplorer/assets/7627862/65581d9e-6c05-4fde-9105-c574016c377c)

**Comment by trananhmanh89** [comment]
> Hello,
> 
> I am using the latest version of Joomla and FF explorer and I am having the exact same issue. Could you please help?
> 
> Joomla version: 4.3.1 FF Explorer version: 1.0.7
> 
> ![ff-explorer-worng-column-name](https://user-images.githubusercontent.com/7627862/240352334-65581d9e-6c05-4fde-9105-c574016c377c.PNG)

could you send me the table that has issue?
